EMAIL_SENDER = "yourgmail@gmail.com"
EMAIL_PASSWORD = "your_app_password"
EMAIL_RECEIVER = "receiver@gmail.com"

TWILIO_SID = "YOUR_TWILIO_SID"
TWILIO_TOKEN = "YOUR_TWILIO_TOKEN"
TWILIO_PHONE = "+1XXXXXXXXXX"
RECEIVER_PHONE = "+91XXXXXXXXXX"

EAR_THRESHOLD = 0.25
YAWN_THRESHOLD = 20
DROWSY_FRAMES = 20